//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceHistoryRecord.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StageStep
    {
        public int StageStepsID { get; set; }
        public int ComponentID { get; set; }
        public int StageID { get; set; }
        public int Sequence { get; set; }
        public int StepTypeID { get; set; }
        public string DocumentTemp { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual ProductStage ProductStage { get; set; }
        public virtual StepType StepType { get; set; }
    }
}
